### ISSUE TITLE
Design Iterieren

### ISSUE THREAD

**Issue by leostraub** [ID-Start-Winter22/chat-team-9#13]
Iterieren Sie weiter die bereits gestalteten Items (Look&Feel): 

- Icon
- Bot Name
- Charakter und Tone-of-voice (Tonalität der Texte)

**Comment by leostraub** [comment]
https://docs.google.com/presentation/d/1ktl52pCFMTz4AFKQTcacEHlKi7CE4Nm5MNPpRtkIYdE/edit?usp=sharing

**Comment by SchlechtePoesieIstProgramm** [comment]
Passt. Alles Top
