### ISSUE TITLE
Eine Liste von Artists ausgeben

### ISSUE THREAD

**Issue by SchlechtePoesieIstProgramm** [ID-Start-Winter22/chat-team-9#14]
Der Bot soll eine Liste von Artists ausgeben, die ähnlich zum gesuchten Artist sind. Ebenfalls soll die ausgegebene Liste 6 unterschiedliche Artists enthalten.

**Comment by SchlechtePoesieIstProgramm** [comment]
Ist erledigt. Leo kann ja mal drüber schauen

**Comment by leostraub** [comment]
Passt
