### ISSUE TITLE
Vorgefertigte Antwortmöglichkeiten

### ISSUE THREAD

**Issue by SchlechtePoesieIstProgramm** [ID-Start-Winter22/chat-team-9#3]
## Story

Als Nutzer will ich vorgefertigte Antwortmöglichkeiten haben, um eine schnellen und leichten  Zugang zum Chat-Bot habe

**Comment by SchlechtePoesieIstProgramm** [comment]
Ein paar Vorgefertigte Antwortmöglichkeiten existieren jetzt. Ich bin offen für Vorschläge für weiter Buttons

**Comment by leostraub** [comment]
Buttons sind implementiert.
