### ISSUE TITLE
implementieren der "Ähnliche Interpreten"

### ISSUE THREAD

**Issue by leostraub** [ID-Start-Winter22/chat-team-9#6]
implementieren der "Ähnliche Interpreten
wenn der Nutzer dem bot einen Interpret der ihm gefällt mitteilt werden dem Nutzer ähnliche Interpreten vorgeschlagen.

**Comment by SchlechtePoesieIstProgramm** [comment]
Ähnliche Artists sind eingefügt. Da kann ja mal jemand drüber schauen
